blank_issues_enabled: false
contact_links:
  - name: Question/Discussion --> Slack
    url: https://app.slack.com/huddle/TCRE7F880/CCRE7FLPJ
    about: Please ask questions or discuss topic on the agrirouter Slack.
